#include "sapureca.th"

namespace sapureca
using namespace sapureca
using namespace naldodj.games

function u_SapuRecaRun()
return(sapureca.SapuReca():Run())

class SapuReca
   static method Run() as logical
end class

static method Run() class SapuReca

    local lRun as logical

    local oController as object

    oController:=SapuRecaController():New()

    lRun:=oController:CanExecute()

    if (lRun)
        lRun:=oController:Activate()
        if (lRun)
            oController:DeActivate()
        endif
    endif

    MsObjects():FreeObjects(@oController)

return(lRun)
