/*----------------------------------------------------------------------

     _  _        _                  _
  __| |(_) _ __ | |_   ___    ___  | | ___
 / _` || || '__|| __| / _ \  / _ \ | |/ __|
| (_| || || |   | |_ | (_) || (_) || |\__ \
 \__,_||_||_|    \__| \___/  \___/ |_||___/

 The source code `naldodj.games.DirTools.tlpp` is based on a more detailed and feature-rich
source code, `dna.tech.DirTools.tlpp`, and implements part of the functionalities
present in the latter.

*/

#include "parmtype.ch"
#include "directry.ch"
#include "tlpp-core.th"

namespace naldodj.games
using namespace naldodj.games

class DirTools

    static method MakeDir(cDirMake as character,lShowMsg as logical) as logical
    static method MakeFileDir(cDirMake as character,lShowMsg as logical) as logical

    static method DirRemove(cDirRoot as character,cDirRemove as character,lRemoveAll as logical) as logical

end class

static method MakeDir(cDirMake,lShowMsg) class DirTools
    local lIsDir as logical
    paramtype 1 var cDirMake as character
    paramtype 2 var lShowMsg as logical optional default .F.
    if ("/"$cDirMake)
        cDirMake:=StrTran(cDirMake,"/","\")
    endif
    lIsDir:=lIsDir(cDirMake)
    if (!lIsDir)
        lIsDir:=DirTools():MakeFileDir(cDirMake,lShowMsg)
    endif
    lIsDir:=lIsDir(cDirMake)
    if (!lIsDir)
        FWMakeDir(cDirMake,lShowMsg)
    endif
    return(lIsDir)

static method MakeFileDir(cDirMake,lShowMsg) class DirTools

    local aDirs as array

    local cExt as character
    local cFile as character
    local cPath as character
    local cDrive as character
    local cFullPath as character

    local lIsDir as logical

    local nAttempt:=0 as numeric
    local nAttempts as numeric

    paramtype 1 var cDirMake as character
    paramtype 2 var lShowMsg as logical optional default .F.

    cExt:=""
    cFile:=""
    cPath:=""
    cDrive:=""

    splitPath(cDirMake,@cDrive,@cPath,@cFile,@cExt)

    cFullPath:=cDrive
    cFullPath+=cPath

    aDirs:=StrTokArr2(cFullPath,"\",.T.)
    nAttempts:=Len(aDirs)

    lIsDir:=DirMake(cFullPath,@cDrive,@cPath,@cFile,@cExt,@lShowMsg)
    while (!lIsDir)
        lIsDir:=DirMake(cFullPath,@cDrive,@cPath,@cFile,@cExt,@lShowMsg)
        if (lIsDir)
            exit
        endif
        if (++nAttempt>nAttempts)
            exit
        endif
    end while

    FWFreeArray(@aDirs)

    return(lIsDir)

static method DirRemove(cDirRoot,cDirRemove,lRemoveAll) class DirTools

    local aDirs as array

    local cExt as character
    local cFile as character
    local cPath as character
    local cDrive as character

    local cFullPathRoot as character

    local lDirRemove as logical

    local nAttempt:=0 as numeric
    local nAttempts as numeric

    paramtype 1 var cDirRoot as character
    paramtype 2 var cDirRemove as character optional default cDirRoot
    paramtype 3 var lRemoveAll as logical optional default .F.

    cExt:=""
    cFile:=""
    cPath:=""
    cDrive:=""

    splitPath(cDirRoot,@cDrive,@cPath,@cFile,@cExt)

    cFullPathRoot:=cDrive
    cFullPathRoot+=cPath

    lDirRemove:=RemoveDir(cFullPathRoot,cDirRemove,@cDrive,@cPath,@cFile,@cExt,@lRemoveAll)
    while (!lDirRemove)
        lDirRemove:=RemoveDir(@cFullPathRoot,@cDirRemove,@cDrive,@cPath,@cFile,@cExt,@lRemoveAll)
        if (lDirRemove)
            exit
        endif
        if (++nAttempt>nAttempts)
            exit
        endif
    end while

    FWFreeArray(@aDirs)

    return(lDirRemove)

static function DirMake(cDirMake as character,cDrive as character,cPath as character,cFile as character,cExt as character,lShowMsg as logical) as logical

    local aDirectory as array

    local cDirectory as character
    local cTDirectory as character

    local lIsDir as logical

    local nD as numeric
    local nJ as numeric

    lIsDir:=lIsDir(cDirMake)

    if (!lIsDir)

        aDirectory:=StrTokArr2(cDirMake,"\",.T.)

        cTDirectory:=""

        nJ:=len(aDirectory)
        for nD:=1 to nJ
            cDirectory:=aDirectory[nD]
            if (empty(cDirectory))
                loop
            endif
            cTDirectory+=if(cDrive$cDirectory,"","\")
            cTDirectory+=cDirectory
            cTDirectory+="\"
            cTDirectory:=StrTran(cTDirectory,"\\","\")
            if (lIsDir:=lIsDir(cTDirectory))
                loop
            endif
            if (!(lIsDir:=FWMakeDir(cTDirectory,lShowMsg)))
                exit
            endif
        next nD

        lIsDir:=lIsDir(cDirMake)

    endif

    FWFreeArray(@aDirectory)

    return(lIsDir)

static function RemoveDir(cRootDir as character,cRemoveDir as character,cDrive as character,cPath as character,cFile as character,cExt as character,lRemoveAll as logical) as logical

    local aFiles as array
    local aDirectory as array
    local aSubDirectory as array

    local cDirectory as character
    local cTDirectory as character
    local cRootDirBas:=cRootDir as character
    local cSubDirectory as character
    local cFullPathFile as character

    local lRemoveDir as logical

    local nD,nJ as numeric
    local nFile,nFiles as numeric
    local nSubDirectory,nSubDirectories as numeric

    lRemoveDir:=!lIsDir(cRootDir)

    if (!lRemoveDir)

        aDirectory:=StrTokArr2(cRootDir,"\",.T.)

        cTDirectory:=""

        nJ:=len(aDirectory)
        for nD:=nJ to 1 step -1
            cDirectory:=aDirectory[nD]
            if (empty(cDirectory))
                loop
            endif
            cTDirectory:=if(cDrive$cDirectory,"","\")
            cTDirectory+=cDirectory
            cTDirectory+="\"
            cTDirectory:=StrTran(cTDirectory,"\\","\")
            if (!(lRemoveDir:=lIsDir(cRootDir)))
                loop
            endif
            if (cTDirectory$Right(cRootDir,Len(cTDirectory)))
                lRemoveDir:=DirRemove(cRootDir)
                if (!lRemoveDir)
                    if (lRemoveAll)
                        aSubDirectory:=Directory(cRootDir+"*.*","D")
                        nSubDirectories:=Len(aSubDirectory)
                        nFile:=0
                        while ((nFile:=aScan(aSubDirectory,{|x|((x[F_ATTR]!="D").or.(x[F_NAME]==".").or.(x[F_NAME]==".."))},++nFile))>0)
                            aDel(aSubDirectory,nFile--)
                            aSize(aSubDirectory,(--nSubDirectories))
                        end while
                        for nSubDirectory:=1 to nSubDirectories
                            cSubDirectory:=cRootDir
                            cSubDirectory+=aSubDirectory[nSubDirectory][F_NAME]
                            if (Right(cSubDirectory,1)!="\")
                                cSubDirectory+="\"
                            endif
                            aFiles:=Directory(cSubDirectory+"*.*")
                            nFiles:=Len(aFiles)
                            for nFile:=1 to nFiles
                                cFullPathFile:=cSubDirectory
                                cFullPathFile+=aFiles[nFile][F_NAME]
                                fErase(cFullPathFile)
                            next nFile
                            FWFreeArray(@aFiles)
                            DirTools():DirRemove(cSubDirectory,cSubDirectory,.T.)
                        next nSubDirectory
                        FWFreeArray(@aSubDirectory)
                    endif
                    lRemoveDir:=!lIsDir(cRootDir)
                    if (!lRemoveDir)
                        lRemoveDir:=DirRemove(cRootDir)
                    endif
                    if (!lRemoveDir)
                        exit
                    endif
                endif
                cRootDir:=StrTran(cRootDir,cTDirectory,"")
                if (Right(cRootDir,1)<>"\")
                    cRootDir+="\"
                endif
                cRemoveDir:=StrTran(cRemoveDir,cTDirectory,"")
                if (Right(cRemoveDir,1)<>"\")
                    cRemoveDir+="\"
                endif
            endif
        next nD

        lRemoveDir:=!lIsDir(cRootDirBas)

    endif

    FWFreeArray(@aDirectory)

    return(lRemoveDir)
